# конфигурация повторяет тест из статьи
# Carcione, J. M., et al. (1988). "Wave propagation simulation 
# in a linear viscoelastic medium"

verbose = false
dt = {dt}
steps = {steps}

[grids]
    [grid]
        id = elastic
        [node]
            name = ElasticMetaNode2D
        [/node]
        [material_node]
        [/material_node]
        [material]
            c1 = 2941.0473541683
            c2 = 1968.5163825592
            rho = 2000
        [/material]
        [factory]
            name = RectGridFactory
            spacing = {grid_spacing}
            size = {grid_size}
            origin = {grid_origin}
        [/factory]
        [schema]
            name = ElasticRectSchema2DRusanov3
        [/schema]
        [fillers]
            [filler]
                name = RectNoReflectFiller
                axis = 0
                side = 0
            [/filler]
            [filler]
                name = RectNoReflectFiller
                axis = 0
                side = 1
            [/filler]
            [filler]
                name = RectNoReflectFiller
                axis = 1
                side = 0
            [/filler]
            [filler]
                name = RectNoReflectFiller
                axis = 1
                side = 1
            [/filler]
        [/fillers]
        [correctors]
            [corrector]
                name = PointSourceCorrector2D
                index = {impulse_index}
                force = 0.0, {force_coef}
                axis = 1
                save = result/vtk/source.vtk
                [impulse]
                    name = FileInterpolationImpulse
                    [interpolator]
                        name = PiceWiceInterpolator1D
                        file = impulse.txt
                    [/interpolator]
                [/impulse]
            [/corrector]
        [/correctors]
    [/grid]
[/grids]

[contacts]
[/contacts]

[initials]
[/initials]

[savers]
    [saver]
		name = StructuredVTKSaver
		path = result/vtk/%g_%s.vtk
		order = 1
		save = {save_vtk}
		params = v, vx, vy, sxx, syy, sxy
		norms = 1, 0, 0, 0, 0, 0
	[/saver]
    [saver]
        name = SinglePointSaver
        path = result/txt/station_1.txt
        order = 1
        save = 1
        params = vx, vy, sxx, syy, sxy
        norms = 0, 0, 0, 0, 0
        index = {station_1}
        eps = 1e-6
    [/saver]
[/savers]
