# конфигурация повторяет тест из статьи
# Carcione, J. M., et al. (1988). "Wave propagation simulation 
# in a linear viscoelastic medium"

verbose = false
dt = {dt}
steps = {steps}

[grids]
    [grid]
        id = elastic
        [node]
            name = ElasticMetaNode2D
        [/node]
        [material_node]
        [/material_node]
        [material]
            c1 = 2941.0473541683
            c2 = 1968.5163825592
            rho = 2000
        [/material]
        [factory]
            name = RectGridFactory
            spacing = {grid_spaing}
            size = {grid_size}
            origin = 0, 0
        [/factory]
        [schema]
            name = ElasticRectSchema2DRusanov3
        [/schema]
        [fillers]
            [filler]
                name = RectNoReflectFiller
                axis = 0
                side = 0
            [/filler]
            [filler]
                name = RectNoReflectFiller
                axis = 0
                side = 1
            [/filler]
            [filler]
                name = RectNoReflectFiller
                axis = 1
                side = 0
            [/filler]
            [filler]
                name = RectNoReflectFiller
                axis = 1
                side = 1
            [/filler]
        [/fillers]
        [correctors]
            # [corrector]
            #     name = RightSideViscoelasticCorrector2D
            #     # index = 50, 50, 0
            #     axis = 1
            # [/corrector]
            [corrector]
                name = PointSourceCorrector2D
                index = {impulse_index}
                force = 0.0, {force_coef}
                # compression = 1.0
                axis = 1
                # eps = 0.001
                # save = result/vtk/source.vtk
                # gauss_w = 2
                [impulse]
                    name = FileInterpolationImpulse
                    [interpolator]
                        name = PiceWiceInterpolator1D
                        file = impulse.txt
                    [/interpolator]
                [/impulse]
            [/corrector]
        [/correctors]
    [/grid]
[/grids]

[contacts]
[/contacts]

[initials]
[/initials]

[savers]
[/savers]
