# конфигурация повторяет тест из статьи
# Komatitsch1999 Introduction to the spectral element method 
# forthree-dimensional seismicwavepropagation

verbose = false
dt = {dt}
steps = {steps}

[grids]
    [grid]
        id = viscoelastic_schema
        [node]
            name = ViscoelasticMetaNode2DL1_3_L2_3
        [/node]
        [material_node]
        [/material_node]
        [material]
            rheology = 1
            c1 = 2941.0473541683
            c2 = 1968.5163825592
            rho = 2000
            tau1_e_1 = 0.109527114743452
            tau1_e_2 = 1.070028707488438e-02
            tau1_e_3 = 1.132519034287800e-03
            tau1_s_1 = 8.841941282883074e-02
            tau1_s_2 = 8.841941282883075e-03
            tau1_s_3 = 8.841941282883074e-04
            tau2_e_1 = 0.112028084581976
            tau2_e_2 = 1.093882462934487e-02
            tau2_e_3 = 1.167173427475064e-03
            tau2_s_1 = 8.841941282883074e-02
            tau2_s_2 = 8.841941282883075e-03
            tau2_s_3 = 8.841941282883074e-04
        [/material]
        [factory]
            name = RectGridFactory
            spacing = {grid_spaing}
            size = {grid_size}
            origin = 0, 0
        [/factory]
        [schema]
            name = ViscoelasticRectSchema2DRusanov3L1_3_L2_3
        [/schema]
        [fillers]
            [filler]
                name = RectNoReflectFiller
                axis = 0
                side = 0
            [/filler]
            [filler]
                name = RectNoReflectFiller
                axis = 0
                side = 1
            [/filler]
            [filler]
                name = RectNoReflectFiller
                axis = 1
                side = 0
            [/filler]
            [filler]
                name = RectNoReflectFiller
                axis = 1
                side = 1
            [/filler]
        [/fillers]
        [correctors]
            [corrector]
                name = ViscoelasticPointSourceCorrector2DL1_3_L2_3
                index = {impulse_index}
                # index = 2, 2, 0
                force = 0.0, {force_coef}
                # compression = 1.0
                axis = 1
                # eps = 0.001
                # gauss_w = 2
                [impulse]
                    name = FileInterpolationImpulse
                    [interpolator]
                        name = PiceWiceInterpolator1D
                        file = impulse.txt
                    [/interpolator]
                [/impulse]
            [/corrector]
        [/correctors]
    [/grid]
[/grids]

[contacts]
[/contacts]

[initials]
[/initials]

[savers]
[/savers]
