# конфигурация повторяет тест из статьи
# Carcione, J. M., et al. (1988). "Wave propagation simulation 
# in a linear viscoelastic medium"

verbose = true
dt = {dt}
steps = {steps}

[grids]
    [grid]
        id = viscoelastic
        [node]
            name = ElasticMetaNode2D
        [/node]
        [material_node]
        [/material_node]
        [material]
            c1 = 3190.226435988779
            c2 = 2175.5894496415513
            rho = 2000
        [/material]
        [factory]
            name = RectGridFactory
            spacing = {grid_spaing}
            size = {grid_size}
            origin = 0, 0
        [/factory]
        [schema]
            name = ElasticRectSchema2DRusanov3
        [/schema]
        [fillers]
            [filler]
                name = RectNoReflectFiller
                axis = 0
                side = 0
            [/filler]
            [filler]
                name = RectNoReflectFiller
                axis = 0
                side = 1
            [/filler]
            [filler]
                name = RectNoReflectFiller
                axis = 1
                side = 0
            [/filler]
            [filler]
                name = RectNoReflectFiller
                axis = 1
                side = 1
            [/filler]
        [/fillers]
        [correctors]
            [corrector]
                name = RightSideViscoelasticCorrector2D
                axis = 1
                tau1_e = 0.0325305, 0.0032530
                tau1_s = 0.0311465, 0.0031146
                tau2_e = 0.0332577, 0.0033257 
                tau2_s = 0.0304655, 0.0030465
                phi1 = -28533009667.64002, -285339257801.0052
                phi2 = -48133770738.29415, -481319028767.1131
            [/corrector]
            [corrector]
                name = PointSourceCorrector2D
                index = {impulse_index}
                # index = 2, 2, 0
                force = 0.0, {force_coef}
                # compression = 1.0
                axis = 1
                # eps = 0.001
                save = result/vtk/source.vtk
                # gauss_w = 2
                [impulse]
                    name = FileInterpolationImpulse
                    [interpolator]
                        name = PiceWiceInterpolator1D
                        file = impulse.txt
                    [/interpolator]
                [/impulse]
            [/corrector]
        [/correctors]
    [/grid]
[/grids]

[contacts]
[/contacts]

[initials]
[/initials]

[savers]
    # [saver]
	# 	name = StructuredVTKSaver
	# 	path = result/vtk/%g_%s.vtk
	# 	order = 1
	# 	save = {save_vtk}
	# 	# save = 1
	# 	params = v, vx, vy, sxx, syy, sxy
	# 	norms = 1, 0, 0, 0, 0, 0
	# [/saver]
    [saver]
        name = SinglePointSaver
        path = result/txt/station_1.txt
        order = 1
        save = 1
        params = vx, vy, sxx, syy, sxy
        norms = 0, 0, 0, 0, 0
        index = {station_1}
        eps = 1e-6
    [/saver]
    [saver]
        name = SinglePointSaver
        path = result/txt/station_2.txt
        order = 1
        save = 1
        params = vx, vy, sxx, syy, sxy
        norms = 0, 0, 0, 0, 0
        index = {station_2}
        eps = 1e-6
    [/saver]
    [saver]
        name = SinglePointSaver
        path = result/txt/station_3.txt
        order = 1
        save = 1
        params = vx, vy, sxx, syy, sxy
        norms = 0, 0, 0, 0, 0
        index = {station_3}
        eps = 1e-6
    [/saver]
    [saver]
        name = SinglePointSaver
        path = result/txt/station_4.txt
        order = 1
        save = 1
        params = vx, vy, sxx, syy, sxy
        norms = 0, 0, 0, 0, 0
        index = {station_4}
        eps = 1e-6
    [/saver]
[/savers]
